Repository pagarme/react-scripts-former-kit-dashboard, pull requests merged in 2019-10, with the labels that each got.

#39 Add sync import support
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  package.json
  yarn.lock
Labels: cos:standard

#41 Code splitting - Update mini-css-extract-plugin config
  config/webpack.config.dev.js
  config/webpack.config.prod.js
Labels: bug-fix, cos:standard, devs

#42 Update version
  package.json
Labels: devs, review-needed
